w3c/json-ld-syntax

- common/terms.html
- index.html
@gkellogg I was not sure who you handle the common files, so I preferred to make a separate PR, instead of a direct commit. Tell me what you prefer in future.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/24.html" title="Last updated on Jul 1, 2018, 10:05 AM GMT (b9f7e79)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/24/fd7b35a...b9f7e79.html" title="Last updated on Jul 1, 2018, 10:05 AM GMT (b9f7e79)">Diff</a>
> who's -> whose

- index.html
Fixes #28.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/45.html" title="Last updated on Aug 12, 2018, 6:40 PM GMT (95652b1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/45/40d18d5...95652b1.html" title="Last updated on Aug 12, 2018, 6:40 PM GMT (95652b1)">Diff</a>
> Clarify example using @none.

- common/common.js
- common/extract-examples.rb
- index.html
Hopefully, this clarifies the differences between vocabulary-relative and document-relative resolution.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/95.html" title="Last updated on Nov 29, 2018, 11:17 PM GMT (5fba988)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/95/44fc855...5fba988.html" title="Last updated on Nov 29, 2018, 11:17 PM GMT (5fba988)">Diff</a>
> Add example and description for issue #56.

- index.html
Fixes #85.
cc/ @bertvannuffelen
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/132.html" title="Last updated on Feb 19, 2019, 10:54 PM UTC (da85f57)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/132/f08ced8...da85f57.html" title="Last updated on Feb 19, 2019, 10:54 PM UTC (da85f57)">Diff</a>
> Add a bit more explanation on `@version`.

- index.html
Note, this will need to be updated when vc-data-model changes and their context is updated. Liberties were taken.
Fixes #122.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/133.html" title="Last updated on Feb 22, 2019, 12:15 AM UTC (f9ef6c9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/133/f08ced8...f9ef6c9.html" title="Last updated on Feb 22, 2019, 12:15 AM UTC (f9ef6c9)">Diff</a>
> Update implicit named graph example.

- common/terms.html
- index.html
none of them should be too controversial, but I'd rather have a review, just in case...
> a number of small editorial changes

- common/extract-examples.rb
- index.html
> Change "dc" as a prefix to "dcterms".

- index.html
> Add @pchampin's suggested change to the definition of _graph object_.

- index.html
and change to show the result of compaction where appropriate.
Fixes #179.
cc/ @kasei
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/189.html" title="Last updated on May 29, 2019, 7:23 PM UTC (62ddac6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/189/c13919d...62ddac6.html" title="Last updated on May 29, 2019, 7:23 PM UTC (62ddac6)">Diff</a>
> Update example to indicate inputs and results

- README.md
- index.html.orig
Solves for https://github.com/w3c/json-ld-wg/issues/84
> Add feature frozen text to README

- index.html
as per my action
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/193.html" title="Last updated on Jun 13, 2019, 4:22 PM UTC (6ea443e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/193/c13919d...6ea443e.html" title="Last updated on Jun 13, 2019, 4:22 PM UTC (6ea443e)">Diff</a>
> clarifications as suggested in #170 and w3c/json-ld-wg#85

- index.html
Fixes #149.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/196.html" title="Last updated on Jun 19, 2019, 11:09 PM UTC (373d32c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/196/16c60eb...373d32c.html" title="Last updated on Jun 19, 2019, 11:09 PM UTC (373d32c)">Diff</a>
> Add a Loading Documents section.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/201.html" title="Last updated on Jul 12, 2019, 3:56 PM UTC (804c257)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/201/39ca24f...804c257.html" title="Last updated on Jul 12, 2019, 3:56 PM UTC (804c257)">Diff</a>
> Add sourced context section.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/202.html" title="Last updated on Jul 12, 2019, 4:07 PM UTC (e8840fa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/202/f5741e4...e8840fa.html" title="Last updated on Jul 12, 2019, 4:07 PM UTC (e8840fa)">Diff</a>
> Add Dave Longley as an editor.

- ack-script/acknowledgements.html
- ack-script/separate_acks.json
- common/common.js
- common/terms.html
- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/266.html" title="Last updated on Sep 25, 2019, 4:20 PM UTC (f01cc7b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/266/fecd5c4...f01cc7b.html" title="Last updated on Sep 25, 2019, 4:20 PM UTC (f01cc7b)">Diff</a>
> Update some attributions.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/267.html" title="Last updated on Sep 25, 2019, 7:02 PM UTC (13b2aba)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/267/dbfd7c4...13b2aba.html" title="Last updated on Sep 25, 2019, 7:02 PM UTC (13b2aba)">Diff</a>
> typos and minor improvements

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/270.html" title="Last updated on Sep 26, 2019, 8:31 AM UTC (f62251d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/270/5302c0c...f62251d.html" title="Last updated on Sep 26, 2019, 8:31 AM UTC (f62251d)">Diff</a>
> proposed solution to #261

- ECHIDNA
- index.html
* Set ECHIDNA config for CR.
* Add crEnd and implementationReportURI config parameters.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/299.html" title="Last updated on Nov 16, 2019, 10:36 PM UTC (88a56fe)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/299/233fa04...88a56fe.html" title="Last updated on Nov 16, 2019, 10:36 PM UTC (88a56fe)">Diff</a>
> Preparation for CR

- index.html
Fixes #300.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/307.html" title="Last updated on Nov 21, 2019, 9:51 PM UTC (adbde64)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/307/db875c2...adbde64.html" title="Last updated on Nov 21, 2019, 9:51 PM UTC (adbde64)">Diff</a>
> Update example to actually require `@graph`.

- index.html
For #296.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/301.html" title="Last updated on Nov 20, 2019, 10:48 PM UTC (76063fc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/301/021edaa...76063fc.html" title="Last updated on Nov 20, 2019, 10:48 PM UTC (76063fc)">Diff</a>
> Add note on `@version` being `1.1` not being semantic versioning.

- index.html
Fixes #310.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/315.html" title="Last updated on Nov 26, 2019, 5:10 PM UTC (3aee1ea)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/315/2b406a9...3aee1ea.html" title="Last updated on Nov 26, 2019, 5:10 PM UTC (3aee1ea)">Diff</a>
> MUST NOT => SHOULD NOT on URI schemes.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/319.html" title="Last updated on Dec 18, 2019, 5:57 PM UTC (31306a7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/319/b70f9dd...31306a7.html" title="Last updated on Dec 18, 2019, 5:57 PM UTC (31306a7)">Diff</a>
> proposed note to address #318

- index.html
For #321.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/322.html" title="Last updated on Jan 8, 2020, 6:54 PM UTC (ae0f718)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/322/8a8eead...ae0f718.html" title="Last updated on Jan 8, 2020, 6:54 PM UTC (ae0f718)">Diff</a>
> Update section references into ECMASCRIPT for JSON comparison.

- .travis.yml
- common/jsonld.js
- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/330.html" title="Last updated on Feb 14, 2020, 7:09 PM UTC (ece9c80)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/330/b157315...ece9c80.html" title="Last updated on Feb 14, 2020, 7:09 PM UTC (ece9c80)">Diff</a>
> Add back changes since CR.

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/steltenpower/json-ld-syntax/pull/352.html" title="Last updated on May 10, 2020, 1:36 AM UTC (6ef73ee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/352/4c103ea...steltenpower:6ef73ee.html" title="Last updated on May 10, 2020, 1:36 AM UTC (6ef73ee)">Diff</a>
> typo fixes

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/359.html" title="Last updated on Jul 7, 2020, 3:54 PM UTC (5e6f04e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/359/eef30cf...5e6f04e.html" title="Last updated on Jul 7, 2020, 3:54 PM UTC (5e6f04e)">Diff</a>
> address #358
