- index.html
in named graph examples.
Fixes #27.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/35.html" title="Last updated on Aug 5, 2018, 7:42 PM GMT (3470dfe)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/35/751cd60...3470dfe.html" title="Last updated on Aug 5, 2018, 7:42 PM GMT (3470dfe)">Diff</a>
> Use IRIs instead of semantically-named blank node identifiers

- index.html
Fixes #36.
This is implemented in w3c/json-ld-api#16.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/41.html" title="Last updated on Aug 11, 2018, 9:48 PM GMT (b754d86)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/41/751cd60...b754d86.html" title="Last updated on Aug 11, 2018, 9:48 PM GMT (b754d86)">Diff</a>
> Describe lists containing lists, as motivated by GeoJSON.

- index.html
This is a stab at updating the syntax document to create feature-related sections. I also attempt to clarify some terms.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/47.html" title="Last updated on Aug 16, 2018, 6:25 PM GMT (d3ac68f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/47/e0ea3d2...d3ac68f.html" title="Last updated on Aug 16, 2018, 6:25 PM GMT (d3ac68f)">Diff</a>
> Reorganization syntax document

- index.html
Fixes #12.
Fixes #44.
Removes Microformats section and Fixes #54.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/58.html" title="Last updated on Aug 27, 2018, 1:04 AM GMT (6109d3d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/58/362549c...6109d3d.html" title="Last updated on Aug 27, 2018, 1:04 AM GMT (6109d3d)">Diff</a>
> Minor editorial updates

- common/common.js
- common/terms.html
- index.html
Also generally improve terminology to be more consistent throughout the document.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/62.html" title="Last updated on Aug 27, 2018, 11:59 PM GMT (772d070)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/62/1d528bb...772d070.html" title="Last updated on Aug 27, 2018, 11:59 PM GMT (772d070)">Diff</a>
>  Update change describing the use of `@none` in maps.

- index.html
Fixes #38.
***
(added manually)
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/73.html">Preview</a>
> Improve language around datatype coercion.

- common/terms.html
- index.html
…and generalized RDF datasets.
Fixes #37.
> Mark blank node property labels as obsolete

- index.html
* Improved `@type` keyword definition, and added _Uses of JSON Objects_ section.
* Add a section on keywords to the grammar, and slight improvement to type values.
Addresses #77.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/92.html" title="Last updated on Nov 17, 2018, 7:27 PM GMT (a42ebb3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/92/337f184...a42ebb3.html" title="Last updated on Nov 17, 2018, 7:27 PM GMT (a42ebb3)">Diff</a>
> Improve keyword descriptions

- index.html
Addresses the concerns expressed in #96.
This PR also includes putting the `<base>` handling content in its own section, and clarifies the extraction of a single, targeted data block. I can move those to separate PRs if desired, as they do introduce requirements unrelated to the topic in #96. They do clarify/specify the use of targeting vs. not targeting specific data blocks. But my apologies for the mixed PR.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/97.html" title="Last updated on Nov 30, 2018, 7:08 PM GMT (63017bd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/97/3320d83...63017bd.html" title="Last updated on Nov 30, 2018, 7:08 PM GMT (63017bd)">Diff</a>
> Remove the need for wrapping comment-open/comment-close text in data blocks

- index.html
and not arbitrary data.
Fixes #102.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/104.html" title="Last updated on Dec 6, 2018, 10:25 PM GMT (748466c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/104/b97a16d...748466c.html" title="Last updated on Dec 6, 2018, 10:25 PM GMT (748466c)">Diff</a>
> Clarify that language map values of `@none` are strings

- index.html
Hey @gkellogg thanks for addressing the issue. This hopefully helps with readability in the example.
***
<a href="https://pr-preview.s3.amazonaws.com/WileyLabs/json-ld-syntax/pull/107.html" title="Last updated on Dec 9, 2018, 1:52 AM GMT (fd98fc3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/107/28df8b5...WileyLabs:fd98fc3.html" title="Last updated on Dec 9, 2018, 1:52 AM GMT (fd98fc3)">Diff</a>
> Clean up language in issue #56 example

- Gemfile.lock
- common/extract-examples.rb
- index.html
and update examples to not show automatic decoding.
Fixes #100.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/106.html" title="Last updated on Dec 8, 2018, 7:50 PM GMT (b12a965)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/106/28df8b5...b12a965.html" title="Last updated on Dec 8, 2018, 7:50 PM GMT (b12a965)">Diff</a>
> Make requirement for entity encoding non-normative

- common/terms.html
- index.html
... and the interpretation of an unspecified URL for specifying context or frame.
For #8.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/111.html" title="Last updated on Jan 12, 2019, 8:29 PM UTC (c212913)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/111/6f92b1d...c212913.html" title="Last updated on Jan 12, 2019, 8:29 PM UTC (c212913)">Diff</a>
> Define additional profile URIs

- .travis.yml
- Gemfile.lock
- index.html
which are resolved relative to the `base IRI`. This subsumes the previous usage of allowing just the empty string.
This is for #72.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/114.html" title="Last updated on Jan 12, 2019, 10:45 PM UTC (e3dbac5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/114/174c2f9...e3dbac5.html" title="Last updated on Jan 12, 2019, 10:45 PM UTC (e3dbac5)">Diff</a>
> Update text on vocabulary mapping and `@vocab` to allow relative IRIs

- index.html
Make example 36 "Using a compact IRI as a term" clearer, but only defining `foaf:homepage` using the compact IRI term form.
Fixes #123.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/126.html" title="Last updated on Feb 12, 2019, 11:22 PM UTC (bc3a64c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/126/1533ca9...bc3a64c.html" title="Last updated on Feb 12, 2019, 11:22 PM UTC (bc3a64c)">Diff</a>
> Clarify compact IRI term example

- Gemfile.lock
- index.html
As per my action during last call, here is a first proposal to describe sealed contexts in the Syntax document. A few comments about this text:
* After writing this, I take back what I said about multiple sealed contexts; I think it can work. I'm still not comfortable with sealing individual terms, though (and the algorithm that I am about the propose does not handle them). However I chose not to mention them in this non-normative section, to keep it short enough.
* Resetting `@context` to `null` must also be prevented by sealed contexts, since it resets *all* term definitions. I didn't mention that in the text, though, because the effect of setting `@context` to null is never described in the document (it is in the API doc).
* Finally, I didn't mention "extension points" in sealed …
> Proposed description of sealed contexts

- common/terms.html
- index.html
For #124 and #127.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/130.html" title="Last updated on Feb 15, 2019, 1:25 AM UTC (7031cc2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/130/5776e7f...7031cc2.html" title="Last updated on Feb 15, 2019, 1:25 AM UTC (7031cc2)">Diff</a>
> Editorial issues

- Gemfile.lock
- index.html
…different term definitions on compaction. This includes describing `@type: @none`.
For w3c/json-ld-api#33.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/131.html" title="Last updated on Feb 20, 2019, 6:38 PM UTC (9c1cbcc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/131/f08ced8...9c1cbcc.html" title="Last updated on Feb 20, 2019, 6:38 PM UTC (9c1cbcc)">Diff</a>
> Expand compaction section

- index.html
Relates to w3c/json-ld-framing#28.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/135.html" title="Last updated on Feb 26, 2019, 9:34 PM UTC (e20c54b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/135/1e8d60f...e20c54b.html" title="Last updated on Feb 26, 2019, 9:34 PM UTC (e20c54b)">Diff</a>
> Add grammar pieces for framing.

- .travis.yml
- Gemfile.lock
- common/extract-examples.rb
- common/jsonld.js
- common/terms.html
- index.html
For #4.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/150.html" title="Last updated on Mar 26, 2019, 10:31 PM UTC (7688a73)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/150/ab6be57...7688a73.html" title="Last updated on Mar 26, 2019, 10:31 PM UTC (7688a73)">Diff</a>
> Define JSON literal and the `rdf:JSON` datatype.

- index.html
I think the current phrasing is actually inaccurate. It seemed to imply (at least to me, a non-native speaker) that *one* equal member was enough for the objects to be considered equal.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/152.html" title="Last updated on Mar 27, 2019, 4:54 PM UTC (36ece32)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/152/1e85d7a...36ece32.html" title="Last updated on Mar 27, 2019, 4:54 PM UTC (36ece32)">Diff</a>
> Better phrasing of object equality

- index.html
If it's decided to change the naming from `@sealed` to `@protected`, here's a patch.
***
<a href="https://pr-preview.s3.amazonaws.com/davidlehn/json-ld-syntax/pull/142.html" title="Last updated on Mar 1, 2019, 2:17 AM UTC (60cd846)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/142/9b80a30...davidlehn:60cd846.html" title="Last updated on Mar 1, 2019, 2:17 AM UTC (60cd846)">Diff</a>
> Change from "sealed" to "protected".

- index.html
`"@vocab": "http://sche…ma.org/"`. Sometimes this means using `foaf`, others it means simply using "http://schema.org/" as the context, rather than `@vocab`.
For #144
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/154.html" title="Last updated on Mar 28, 2019, 10:10 PM UTC (151f80c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/154/8c01dfd...151f80c.html" title="Last updated on Mar 28, 2019, 10:10 PM UTC (151f80c)">Diff</a>
> Update default vocabulary used in examples to avoid schema.org

- index.html
NB: marked example 44 as ignored, because it is not supported by the current implementation
> reflected the decisions about #136

- Gemfile.lock
- common/extract-examples.rb
- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/145.html" title="Last updated on Mar 26, 2019, 10:55 PM UTC (f2dc97d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/145/dbb3103...f2dc97d.html" title="Last updated on Mar 26, 2019, 10:55 PM UTC (f2dc97d)">Diff</a>
> describing property-based indexing as a variant of data indexing

- common/extract-examples.rb
- index.html
if they're too large to represent as integers.
> Add caveat on numbers being represented as double

- index.html
which would expand to something other than they key itself.
Note, this represents a change from 1.0 behavior.
For #155.
> Disallow terms which are compact IRIs or absolute IRIs

- Gemfile.lock
- index.html
For w3c/json-ld-api#66.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/167.html" title="Last updated on Apr 30, 2019, 9:15 PM UTC (6a54179)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/167/449c65f...6a54179.html" title="Last updated on Apr 30, 2019, 9:15 PM UTC (6a54179)">Diff</a>
> Add a section on using HTML documents for contexts (and frames).

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/171.html" title="Last updated on May 6, 2019, 9:44 PM UTC (9bfbfe9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/171/6651b11...9bfbfe9.html" title="Last updated on May 6, 2019, 9:44 PM UTC (9bfbfe9)">Diff</a>
> Fix term-selection description for 1.0 mode, not JSON-LD 1.0 spec

- index.html
This correction is for example 42 regarding scoped contexts:
```
{
"@context": {
"@vocab": "http://example.com/vocab/"
"property": {
"@id": "http://example.com/vocab/property",
"@context": {
"term1": "http://example.com/vocab/term1"
↑ Scoped context for "property" defines term1
},
},
"Type1": {
"@id": "http://example.com/vocab/Type1",
"@context": {
"term2": "http://example.com/vocab/term3"
↑ Scoped context for "Type1" defines term3
},
},
"Type2": {
"@id": "http://example.com/vocab/Type2",
"@context": {
"term3": "http://example.com/vocab/term4"
↑ Scoped context for "Type2" defines term4
},
},
},
"property": {
"@context": {
"term2": "http://example.com/vocab/term2"
↑ Embedded context defines term2
},
"@type": ["Type2", "Type1"],
"term1": "a",
"term2": "b",
"term3": "c",
"term4": "d",
}
} …
```
> Correct term assignment to proper IRI in example 42.

- index.html
This looks like just an oversight and title should match the example above.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/181.html" title="Last updated on May 17, 2019, 7:04 PM UTC (c18ae50)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/181/06a9111...c18ae50.html" title="Last updated on May 17, 2019, 7:04 PM UTC (c18ae50)">Diff</a>
> Fix example title.

- common/extract-examples.rb
- index.html
Add -l argument to just run example at line, instead of -n for exampl…e number.
Add linting of RDF results, unless data-no-lint is used.
Update examples to either skip linting, or lint cleanly.
Fixes #180
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/182.html" title="Last updated on May 18, 2019, 11:28 PM UTC (c46d443)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/182/b36d185...c46d443.html" title="Last updated on May 18, 2019, 11:28 PM UTC (c46d443)">Diff</a>
> Update examples to either skip linting, or lint cleanly.

- common/terms.html
It wasn't a typo, but could be more complete.
"An object expressed as a value such as a string, number or in expanded form **as a value object**."
cc/@kasei
Fixes #176.
> Be more clear about literals as value objects

- index.html
Fixes #178.
If this is acceptable, will apply stying changes to API and Framing docs.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/188.html" title="Last updated on May 27, 2019, 6:51 PM UTC (22d0b4f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/188/a3a0224...22d0b4f.html" title="Last updated on May 27, 2019, 6:51 PM UTC (22d0b4f)">Diff</a>
> Update example label styling (for contexts, etc.) and invert tabs for example 26/27

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/190.html" title="Last updated on Jun 10, 2019, 10:28 PM UTC (a63b99c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/190/22176e9...a63b99c.html" title="Last updated on Jun 10, 2019, 10:28 PM UTC (a63b99c)">Diff</a>
> Protected terms can be redefined, if identical

- index.html
Add changes for type-scoped contexts.
Fixes #174.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/195.html" title="Last updated on Jun 19, 2019, 11:14 PM UTC (08b3a1c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/195/16c60eb...08b3a1c.html" title="Last updated on Jun 19, 2019, 11:14 PM UTC (08b3a1c)">Diff</a>
> Describe that type-scoped contexts are only in affect on the node objects in which they're used

- common/algorithm-terms.html
- common/common.js
- common/terms.html
- common/typographical-conventions.html
- index.html
This mirrors changes to the API document, but also attempts to clean up our shared terms to reference outside specs as much as possible.
Note that there is still some overlap between WebIDL definitions and ECMASCRIPT, particularly for _dictionary_ and _dictionary member_.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/198.html" title="Last updated on Jul 9, 2019, 8:37 PM UTC (0f6e413)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/198/3ed3de7...0f6e413.html" title="Last updated on Jul 9, 2019, 8:37 PM UTC (0f6e413)">Diff</a>
> Respec updates

- Gemfile
- Gemfile.lock
- common/extract-examples.rb
- index.html
Fixes #174.
(Still requires description of `@source`. Examples will fail until changes made to Ruby implementation, pending agreement on this and w3c/api#112.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/200.html" title="Last updated on Jul 12, 2019, 3:58 PM UTC (0384304)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/200/f5741e4...0384304.html" title="Last updated on Jul 12, 2019, 3:58 PM UTC (0384304)">Diff</a>
> Add section for `@propagate` and stub for `@import`.

- common/terms.html
- index.html
Use type-scoped and property-scoped terms, and take advantage of "context definition" as the shape of a map used as a context.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/203.html" title="Last updated on Jul 12, 2019, 11:00 PM UTC (2cf0188)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/203/7023fd1...2cf0188.html" title="Last updated on Jul 12, 2019, 11:00 PM UTC (2cf0188)">Diff</a>
> Context definitions

- common/algorithm-terms.html
- common/terms.html
- index.html
* Reorganize and re-introduce terms.
* Add explicit `data-cite` on all defined terms, to localize them to a particular spec.
* Simplifies some imported terms.
@pchampin see if this is what you had in mind. We could consolidate all imported terms.
@marcoscaceres this adds a `data-cite` to each shared term we define, which seems like what we need to do.
Fixes #185.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/206.html" title="Last updated on Jul 20, 2019, 9:54 PM UTC (1121d34)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/206/cadf696...1121d34.html" title="Last updated on Jul 20, 2019, 9:54 PM UTC (1121d34)">Diff</a>
> Terms update

- index.html
(I hope this PR for a PR works:-)
I have made a change on the section of `@included` to emphasize the simple bush feature, but also maintaining the original example. I am sure the text needs harmonization as for the style.
I was also not sure about the paragraph on the JSON API; I have never used that thing, so I cannot comment on it. I am actually not sure it is worth keeping it here; it is not necessarily relevant imho. (or should be put as a note if we really want to keep to it).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/209.html" title="Last updated on Aug 1, 2019, 8:34 PM UTC (eea1017)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/209/4068a74...eea1017.html" title="Last updated on Aug 1, 2019, 8:34 PM UTC …
> Added the example for bushes

- Gemfile.lock
- common/jsonld.js
- common/terms.html
- index.html
For #19.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/208.html" title="Last updated on Aug 2, 2019, 5:28 PM UTC (809409a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/208/ab5050d...809409a.html" title="Last updated on Aug 2, 2019, 5:28 PM UTC (809409a)">Diff</a>
> Describe included blocks.

- common/terms.html
- index.html
to specifically allow compact IRI and term.
Fixes w3c/json-ld-syntax#184.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/210.html" title="Last updated on Aug 7, 2019, 5:22 PM UTC (35e044c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/210/48beb5c...35e044c.html" title="Last updated on Aug 7, 2019, 5:22 PM UTC (35e044c)">Diff</a>
> Update definition for _vocabulary mapping_

- index.html
…and add an Alternate Document Location section.
For #204.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/211.html" title="Last updated on Aug 14, 2019, 4:33 PM UTC (dc5855e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/211/6dc0e7e...dc5855e.html" title="Last updated on Aug 14, 2019, 4:33 PM UTC (dc5855e)">Diff</a>
> Add containing section on Modifying Behavior with Link Relationships

- index.html
Almost all the changes are purely editorial (misspelling, whitespace issues, etc.) The only minimally more substantial change is in 4.9.2: that is also a 1.1 issues, and the corresponding language has been put in line with the other, similar subsections.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/264.html" title="Last updated on Sep 23, 2019, 8:24 PM UTC (687db49)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/264/bb3e08a...687db49.html" title="Last updated on Sep 23, 2019, 8:24 PM UTC (687db49)">Diff</a>
> Minor editorial issues

- Gemfile.lock
- common/common.js
- common/terms.html
- index.html
* "This specification defines JSON-LD" => "This specification defines JSON-LD 1.1". Fixes #217. 
* Remove "if desired" Fixes #218.
* Improve _default language_ definition. Fixes #219.
* it's => its fixes. Fixes #221, fixes #223, and fixes #239.
* ore => or. Fixes #222. 
* Simplify simplicity. Fixes #224.
* Improve data model overview. For #225.
* Clarify that literals are not blank nodes. Fixes #226.
* Improve definition of `@nest`. Fixes #227.
* Update `@none` definition. Fixes #228.
* sccope => scope. Fixes #229.
* Clarify that `@version` is set to `1.1`, not `"json-ld-1.1"`. Fixes #230.
* Improve requirements of terms. Improve requirements of terms.
* Reference security considerations for remote contexts. Fixes #232.
* Update local dfns to not be links by removing data-cite. Fixes …
> Azaroth suggestions

- index.html
also
- reordered the keywords (in alphabetical order)
in the def of "context definition"
- removed spurious keywords in the def "expanded term definitions"
(@import, @propagate)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/268.html" title="Last updated on Sep 25, 2019, 7:45 PM UTC (5b567e1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/268/dbfd7c4...5b567e1.html" title="Last updated on Sep 25, 2019, 7:45 PM UTC (5b567e1)">Diff</a>
> added missing keywords in sections 1.7, 9.15 and 9.16, addressing #262

- index.html
* Improve data indexing examples. Fixes #253.
* Use `@base` in id-indexing example. Fixes #254.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/271.html" title="Last updated on Sep 27, 2019, 7:49 PM UTC (a06058c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/271/5a6e511...a06058c.html" title="Last updated on Sep 27, 2019, 7:49 PM UTC (a06058c)">Diff</a>
> More azaroth fixes

- index.html
and add more to the grammar.
For #246.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/272.html" title="Last updated on Sep 28, 2019, 5:35 PM UTC (eaa444e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/272/d28d3de...eaa444e.html" title="Last updated on Sep 28, 2019, 5:35 PM UTC (eaa444e)">Diff</a>
> Improve description of keyword aliases using `@protected`

- index.html
... Locating a Specific JSON-LD Script Element example.
Fixes #256.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/274.html" title="Last updated on Sep 30, 2019, 7:02 PM UTC (e96916f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/274/99288f7...e96916f.html" title="Last updated on Sep 30, 2019, 7:02 PM UTC (e96916f)">Diff</a>
> Update fragment used in 7.3

- index.html
Fixes #258.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/275.html" title="Last updated on Sep 30, 2019, 7:13 PM UTC (3af6a7f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/275/99288f7...3af6a7f.html" title="Last updated on Sep 30, 2019, 7:13 PM UTC (3af6a7f)">Diff</a>
> Add note that `null` is preserved in JSON literals.

- index.html
Fixes w3c/json-ld-wg#116.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/281.html" title="Last updated on Oct 4, 2019, 7:14 PM UTC (f31c9dd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/281/3a9dbec...f31c9dd.html" title="Last updated on Oct 4, 2019, 7:14 PM UTC (f31c9dd)">Diff</a>
> Add link to the API test suite.

- Gemfile.lock
- common/extract-examples.rb
- common/terms.html
- index.html
Update examples to not downcase language.
For https://github.com/w3c/json-ld-api/issues/167.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/283.html" title="Last updated on Oct 14, 2019, 11:34 PM UTC (f06828a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/283/f2f67f3...f06828a.html" title="Last updated on Oct 14, 2019, 11:34 PM UTC (f06828a)">Diff</a>
> Language tag

- Gemfile.lock
- common/terms.html
- index.html
Describe implicit behavior as being for JSON-LD 1.1, with overrides available if `processingMode` set explicitly to `json-ld-1.0`.
For w3c/json-ld-api#161.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/284.html" title="Last updated on Oct 18, 2019, 8:49 PM UTC (804ae28)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/284/51f5007...804ae28.html" title="Last updated on Oct 18, 2019, 8:49 PM UTC (804ae28)">Diff</a>
> Lazy eval version

- index.html
Fixes #269.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/286.html" title="Last updated on Oct 21, 2019, 5:27 PM UTC (c2bf39e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/286/acc0729...c2bf39e.html" title="Last updated on Oct 21, 2019, 5:27 PM UTC (c2bf39e)">Diff</a>
> Improve normative definition of `@type`.

- common/terms.html
- index.html
... use _IRI reference_ where appropriate, and replace _relative IRI_ with _relative IRI reference_.
For #288.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/289.html" title="Last updated on Nov 2, 2019, 6:57 PM UTC (19ffb44)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/289/44ecfe8...19ffb44.html" title="Last updated on Nov 2, 2019, 6:57 PM UTC (19ffb44)">Diff</a>
> Update use of _IRI_ to obviate _absolute IRI_

- index.html
to allow `+ld+json`… to be used as a structured subtype for new base types.
Allow file extensions to be associated with profile parameters to `application/ld+json`.
For #287.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/291.html" title="Last updated on Nov 6, 2019, 5:50 PM UTC (1b5048a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/291/ee9e486...1b5048a.html" title="Last updated on Nov 6, 2019, 5:50 PM UTC (1b5048a)">Diff</a>
> Add additional wording to the IANA considerations

- index.html
followed by one or more ALPHA characters.
For w3c/json-ld-api#191.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/293.html" title="Last updated on Nov 11, 2019, 7:22 PM UTC (efc725c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/293/411f708...efc725c.html" title="Last updated on Nov 11, 2019, 7:22 PM UTC (efc725c)">Diff</a>
> Describe forward-compatibility issues with terms starting with `@`

- common/terms.html
- index.html
Addresses #294 .
Two remarks about this PR:
* due to some sections not being normative anymore, 5 references have moved from normative references to non-normative references:
* INFRA
*JSON-LD10 (now duplicated with JSON-LD, btw)
* LINKED DATA
* RFC5234 (ANBF)
* WEBIDL
I don't think any of this is a problem for the SYNTAX document, but others might disagree.
* Should term mentions in the rest of the document (and other documents) point to the normative definition in §9 rather than to §1.4? It seems to make more sense, but on the other hand, definitions in §1.4 are more explicative and readable, and they point to examples in sections 3 and 4... Plus, I don't have the respec skill to do it (I tried and I failed).
An alternative would be to add, in each definition where this is relevant, a …
> Clean informative sections

- index.html
Changed example 115 and its description to address @Fak3's remark.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/302.html" title="Last updated on Nov 21, 2019, 1:55 PM UTC (664b28f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/302/021edaa...664b28f.html" title="Last updated on Nov 21, 2019, 1:55 PM UTC (664b28f)">Diff</a>
> Address issue #300

- common/terms.html
- index.html
* Add clarification to keyword aliasing and remove MUST NOT be aliased description, as this implies that doing so would lead to an exception, which it does not.
* Remove normative language from a note in the Aliasing Keywords Section.
* Be explicit about where keywords can and cannot be aliased in the normative Keywords section.
* Reference `#using-set-with-type` for examples on using `@type` in a context.
For #308 and for #309.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/312.html" title="Last updated on Nov 25, 2019, 9:50 PM UTC (d230aee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/312/4ef8738...d230aee.html" title="Last updated on Nov 25, 2019, 9:50 PM UTC (d230aee)">Diff</a>
> Keyword aliases

- index.html
The triple emitted twice is "ex2:fred ex2:knows ex1:barney"
***
<a href="https://pr-preview.s3.amazonaws.com/Fak3/json-ld-syntax/pull/314.html" title="Last updated on Nov 26, 2019, 9:52 AM UTC (89f3de4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/314/ee7f17d...Fak3:89f3de4.html" title="Last updated on Nov 26, 2019, 9:52 AM UTC (89f3de4)">Diff</a>
> Fix Note for example 65

- index.html
Fixes #311.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/317.html" title="Last updated on Dec 9, 2019, 9:46 PM UTC (0ebc014)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/317/ece751d...0ebc014.html" title="Last updated on Dec 9, 2019, 9:46 PM UTC (0ebc014)">Diff</a>
> Describe resolution of remote context documents using relative URLs.

- index.html
addressing #323
Note that the description of the canonical form, which used to be non-normative (and using SHOULD) is now normative and uses MUST. It seemed inappropriate to define the value space non-normatively... :-/
As a consequence, the corresponding text in [API 8.6 Data Round Tripping](http://localhost:8000/json-ld-api/#data-round-tripping) is states:
> The canonical lexical form of a JSON literal value is non-normative, 
and still uses SHOULD. I guess we should update it as well?
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/325.html" title="Last updated on Jan 24, 2020, 4:37 PM UTC (a25e7e5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/325/597a8c4...a25e7e5.html" title="Last updated on Jan 24, 2020, 4:37 PM UTC …
> changed definition of the rdf:JSON datatype

- Gemfile.lock
- common/algorithm-terms.html
- index.html
and Compound Literal to lower case language tags.
For w3c/json-ld-api#337.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/327.html" title="Last updated on Jan 29, 2020, 6:05 PM UTC (ea2bc38)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/327/f55efdc...ea2bc38.html" title="Last updated on Jan 29, 2020, 6:05 PM UTC (ea2bc38)">Diff</a>
> Update description of i18n datatype

- index.html
See https://lists.w3.org/Archives/Public/public-json-ld-wg/2020Feb/0024.html.
> It seems that the *+ld+json is an issue for IETF and cannot be done.
> I think that, at this point, we should remove this thing from the JSON-LD spec and finalize the spec with ld+json. I do not think we should make the progress towards a Rec stop because of that.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/331.html" title="Last updated on Feb 22, 2020, 1:47 AM UTC (7e1ee2d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/331/17dd029...7e1ee2d.html" title="Last updated on Feb 22, 2020, 1:47 AM UTC (7e1ee2d)">Diff</a>
> Comment out `+ld+json` mime extensions.

- index.html
and not that this affects both expansion and compaction.
Fixes #339.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/340.html" title="Last updated on Mar 22, 2020, 8:41 PM UTC (d40f805)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/340/65a8c08...d40f805.html" title="Last updated on Mar 22, 2020, 8:41 PM UTC (d40f805)">Diff</a>
> Describe `@prefix: false` behavior

- common/terms.html
…to point to Contexts Definitions.
Move reference to Value Objects up to the _value object_ term.
Fixes #341.
> Update normative reference for _vocabulary mapping_ term

- index.html
Closes #255 ... finally!
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Apr 14, 2020, 6:07 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawcdn.githack.com%2Fw3c%2Fjson-ld-syntax%2F10a2770a5b4e8a217dea309daea69a634ba43505%2Findex.html%3FisPreview%3Dtrue)
```
Navigation timeout of 30000 ms exceeded
```
_If you don't have enough information above to solve the error by yourself (or to understand to which web service …
> Update included block example based on ones either side

- index.html
- publication-snapshots/PR/Overview.html
At the instruction of PlH I have added a note into the SOTD about this. To make things quicker and avoid problems, I have changed the version of the document already on /TR.
(Oops, I realized I made a spelling mistake in the name of the branch:-)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/350.html" title="Last updated on May 6, 2020, 7:29 PM UTC (0a27e4c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/350/6c4be3d...0a27e4c.html" title="Last updated on May 6, 2020, 7:29 PM UTC (0a27e4c)">Diff</a>
> Added a note on superseding 1.0 into the SOTD

- index.html
For w3c/json-ld-wg#150.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/354.html" title="Last updated on Jun 8, 2020, 12:43 AM UTC (37b1641)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/354/4c103ea...37b1641.html" title="Last updated on Jun 8, 2020, 12:43 AM UTC (37b1641)">Diff</a>
> Remove atrisk notes.

- common/jsonld.js
- index.html
Note that we discuss changing our canonicalization requirements to JCS when it becomes available, which it is now. Perhaps something to take up post-publication.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/357.html" title="Last updated on Jun 30, 2020, 10:25 PM UTC (d1e4f98)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/357/f22165c...d1e4f98.html" title="Last updated on Jun 30, 2020, 10:25 PM UTC (d1e4f98)">Diff</a>
> Change JCS bibref to RFC8785, as it's now published.

- index.html
@iherman this may be overkill, in which case we can simply drop it.
This is to add entry in changes since rec for the HTTP => HTML typo.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/371.html" title="Last updated on Apr 1, 2021, 5:42 PM UTC (1bba07f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/371/0a1ab69...1bba07f.html" title="Last updated on Apr 1, 2021, 5:42 PM UTC (1bba07f)">Diff</a>
> Add a note on the change from HTTP document to HTML document.

- index.html
improve appendix B.1.3 as discussed in #387
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Jun 1, 2022, 7:58 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Fjson-ld-syntax%2F3835c8097f3cff0ec9892d623068eb7db538c484%2Findex.html%3FisPreview%3Dtrue)
```
<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
```
_If you don't have enough …
> address #387

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/OR13/json-ld-syntax/pull/415.html" title="Last updated on Jul 17, 2023, 6:10 PM UTC (790ff22)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/415/54f6d1d...OR13:790ff22.html" title="Last updated on Jul 17, 2023, 6:10 PM UTC (790ff22)">Diff</a>
> Add structured suffix

- index.html
While @direction may be used in a context definition it was only listed under context definition's conditional cases not under context definition's definition.
***
<a href="https://pr-preview.s3.amazonaws.com/Kibubu/json-ld-syntax/pull/439.html" title="Last updated on Aug 2, 2024, 3:49 PM UTC (41e8195)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/439/7bb0d85...Kibubu:41e8195.html" title="Last updated on Aug 2, 2024, 3:49 PM UTC (41e8195)">Diff</a>
> Fix @direction not listed under context definition's definition

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/bretelerjmw/json-ld-syntax/pull/450.html" title="Last updated on Feb 7, 2025, 6:00 PM UTC (57bca38)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/450/bf79c62...bretelerjmw:57bca38.html" title="Last updated on Feb 7, 2025, 6:00 PM UTC (57bca38)">Diff</a>
> Fix typo in example 128 on compacting

- common/terms.html
- index.html
Relates to https://github.com/w3c/json-ld-api/pull/638.
Fixes #461.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/pull/462.html" title="Last updated on Jun 4, 2025, 6:12 PM UTC (b7b05f3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/json-ld-syntax/462/931ebd9...b7b05f3.html" title="Last updated on Jun 4, 2025, 6:12 PM UTC (b7b05f3)">Diff</a>
> Update terminology "term definition" for CANDIDATE CORRECTION 1.
